import dissections_valuations_hilbert_s_third_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace dissections_valuations_hilbert_s_third_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end dissections_valuations_hilbert_s_third_foundation_canonical_lane_mathlib
end HautevilleHouse
